name: Build exa-mcp-server Image

on:
  push:
    paths:
      - "exa-mcp-server/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: exa-mcp-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./exa-mcp-server
          file: ./exa-mcp-server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/exa-mcp-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
