name: Build mcp-proxy-server Image

on:
  push:
    paths:
      - "mcp-proxy-server/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: mcp-proxy-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-proxy-server
          file: ./mcp-proxy-server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mcp-proxy-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
