name: Build Perplexica Image

on:
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: "ItzCrazyKns/Perplexica"
          path: "Perplexica"

      # sed -i 's/OPENAI = ".*"/OPENAI = "${{ secrets.OPENAI_API_KEY }}"/g' Perplexica/config.toml
      # sed -i 's/GROQ = ".*"/GROQ = "${{ secrets.GROQ_API_KEY }}"/g' Perplexica/config.toml
      # sed -i 's/ANTHROPIC = ".*"/ANTHROPIC = "${{ secrets.ANTHROPIC_API_KEY }}"/g' Perplexica/config.toml
      # sed -i 's|OLLAMA = ".*"|OLLAMA = "${{ secrets.OLLAMA_API_URL }}"|' Perplexica/config.toml
      - name: Copy and modify config.toml
        run: |
          cp Perplexica/sample.config.toml Perplexica/config.toml
          sed -i 's|OLLAMA = ".*"|OLLAMA = "${{ secrets.OLLAMA_API_URL }}"|' Perplexica/config.toml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Perplexica
          file: ./Perplexica/backend.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/perplexica-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SEARXNG_API_URL: ${{ secrets.SEARXNG_API_URL }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./Perplexica
          file: ./Perplexica/app.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/perplexica-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL }}
            NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
