name: Build Pytorch Image

on:
  push:
    paths:
      - "Pytorch/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: Pytorch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pytorch:latest
          build-args: |
            SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
